### ISSUE TITLE
Update macOS icon [$30]

### ISSUE THREAD

**Issue by williamparry** [williamparry/cloudRIG#90]
* New macOS icon with colours like this: https://prnt.sc/k44d19
* Make the cloud part of the icon stand out - it looks a bit small in situ
![screen shot 2018-07-09 at 1 28 07 pm](https://user-images.githubusercontent.com/348091/42429367-eebff3a6-837b-11e8-96fc-77b777a1970c.png)

**Comment by Prid13** [comment]
Looks pretty nice, if I may say so myself. Now, to make the cloud stand out a bit better.

![screenshot_267](https://user-images.githubusercontent.com/27897747/42429635-6fc663f0-833a-11e8-9ccd-8403188d98e2.png)

**Comment by Prid13** [comment]
It's almost impossible to incorporate a cloud in the icon while still making the logo look good in low-res on the macOS dock and actually be identifiable. That's why I took a different approach to the word "cloud" and tried adding arrows -- would that work?

![cloudrig logo](https://user-images.githubusercontent.com/27897747/42430445-931c54f4-833f-11e8-80e2-cabe9190dc96.jpg)

![cloudrig macos dock](https://user-images.githubusercontent.com/27897747/42430450-9685ad20-833f-11e8-9669-d8b120bd964f.jpg)

**Comment by Prid13** [comment]
Yet even more logos:

![screenshot_268](https://user-images.githubusercontent.com/27897747/42430581-66cc7586-8340-11e8-9ba1-dd9131b75677.png)
![screenshot_269](https://user-images.githubusercontent.com/27897747/42430582-66e7e618-8340-11e8-8afd-5ed9f94f2618.png)
![screenshot_270](https://user-images.githubusercontent.com/27897747/42430583-670246d4-8340-11e8-8abf-09a87e323e48.png)

**Comment by williamparry** [comment]
hmm they don't really work. I reckon let's keep it with just the controller, new colours and the extra outlining on the clouds.

**Comment by williamparry** [comment]
Nice! Feel free to claim the bounty

**Comment by Prid13** [comment]
Sweet, I'll be able to claim it as soon as you close this issue 👍
